### ISSUE TITLE
Handle NO_MATCH intent for unlimited times

### ISSUE THREAD

**Issue by edayaxin** [actions-on-google/actions-builder-canvas-nodejs#2]
Hello, I created webhookHandler for NO_MATCH intent in my Interactive Canvas app but it can only handle the input for a few times, then the app will come to the conversation end. Is it possible to handle the no_match intent for unlimited times? I'm trying to use conv.intent.query for dictation, so the user input won't match any intent. Any suggestions would be greatly appreciated!

**Comment by Fleker** [comment]
There is no way to match NO_MATCH an indefinite number of times. If you want to handle something like it, you should create an intent that accepts freeform text that is accepted as valid while being able to do more advanced processing in your webhook.

**Comment by edayaxin** [comment]
Thanks Fleker for the pointer. I solved this by adding a new Type with "freeText: {}" and used slot filling to handle it as suggested in the [actions doc ](https://developers.google.com/assistant/conversational/best-practice-nlu#intents).
